name: Release on Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release Plugins on Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifacts from Main Workflow
        uses: actions/download-artifact@v4
        with:
          name: flyway-oceanbase-plugin
      - name: Download Artifacts from Main Workflow
        uses: actions/download-artifact@v4
        with:
          name: trino-oceanbase-plugin
      - name: Download Artifacts from Main Workflow
        uses: actions/download-artifact@v4
        with:
          name: wordpress-oceanbase-plugin

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: OceanBase Ecosystem Plugins v${{ github.ref_name }}
          body: Automated release for version ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: flyway-oceanbase-plugin/target/*.jar
          asset_name: flyway-oceanbase-plugin.jar
          asset_content_type: application/java-archive

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: trino-oceanbase-plugin/target/*.jar
          asset_name: trino-oceanbase-plugin.jar
          asset_content_type: application/java-archive

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: wordpress-oceanbase-plugin/oceanBase-delete-expired-transients.php
          asset_name: oceanBase-delete-expired-transients.php
          asset_content_type: application/php
